### ISSUE TITLE
[Feature request] Possibility of: Dark mode? Markdown formatting?

### ISSUE THREAD

**Issue by Darthagnon** [OnlyDeLtA/NotesMan#2]
Greetings. Would be please be possible to implement a Dark mode and Markdown formatting? Would also be nice imo if the Groups were available as a toggleable column on the left-hand-side.

**Comment by OnlyDeLtA** [comment]
Hi, for Markdown formatting there are no plans for now . 
Dark Theme & Separate column to access Groups in main app window, will sure be implemented in future releases. 
Being a feature request I'm closing this issue, If you have any other feature request/ bug report, open a new issue.
